name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Restore NuGet Packages
      run: dotnet restore
    
    - name: Build
      run: dotnet build
      
    - name: Test
      run: dotnet test --logger "trx;LogFileName=test_results.trx"

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Dependencies
      run: npm ci
        
    - name: Build TypeScript
      run: npm run build
        
    - name: Lint TypeScript
      run: npm run lint
        
    - name: Test TypeScript
      run: npm run test