name: Continuous Integration
on: [push]                      

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      
    
    steps:
    - uses: actions/checkout@v4 
    
    - name: Build
      run: dotnet build
      
    - name: Test
      run: dotnet test

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Dependencies
      working-directory: ./DotnetTemplate.Web
        run: npm install
        
    - name: Build TypeScript
      run: npm run build
        
    - name: Lint TypeScript
      run: npm run lint
        
    - name: Test TypeScript
      run: npm run test